easy_admin:
    design:
        templates:
            layout: 'layout.html.twig'
        menu: 
            - label: 'Paquet'
              icon: 'archive'
              children:
                - { entity: 'Card', icon: 'clone' }
                - { entity: 'Tag', icon: 'tags' }
            - { entity: 'User', icon: 'cog' }
        brand-color: 'orange'
    site_name: 'Admin'
    formats:
        datetime: 'd/m/Y'