easy_admin:
    entities:
        Tag:
            class: App\Entity\Tag
            label: 'Tags'
            list:
                fields: [{property: 'name', label: 'Tag'}, {property: 'cards', label: 'Nombre de cartes'}]
                title: "Parcourez vos tags"
                max_results: 10
                actions: 
                    - { name : 'edit', icon: 'pencil', label: false, css_class: 'btn btn-info' }
                    - { name : 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger' }
                    - { name : 'new', label: "Nouveau tag" }
                    - { name : 'search', label: "Rechercher" }
            form: 
                fields:
                    - { property: 'name', label: 'Nom du tag' }
                actions: 
                    - { name : 'delete', icon: 'trash', label: 'Supprimer ce tag', css_class: 'btn btn-danger' }
            new:
                title: "Ajouter un tag"
            edit:
                title: "Modifier un tag"