easy_admin_bundle:
    # this is just an example; update the value of 'resource' accordingly
    resource: 'App\Controller\AdminController'
    type:     annotation
    prefix:   /admin
login:
    path: security_login
    controller: App\Controller\SecurityController::login
    methods: GET|POST
